# Generated by Django 4.1.3 on 2022-11-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typee', models.CharField(max_length=20)),
                ('quality', models.TextField()),
                ('price', models.IntegerField()),
                ('picture', models.CharField(max_length=255)),
            ],
        ),
    ]
